language: node_js
install:
  - npm ci
script:
  - npm test
deploy:
  provider: heroku
  on:
    branch: master
  api_key:
    secure: JKFNqsxm269lpNEBrHXDCESFRvdQLuMSOhnDFi1nxjyeSjzcXLRlrAvaFJPf4mzE5/7MVkJNjo7rxxRRMWHc35BzOak0dhuqsK+Rn6X63ZCs7fqwTQGgTXs5vpC512ABfQscGML+Ptuz8O3KuHuO+njkTTEXZG9IqMgtQ60jpXh4LC+IN9AYh3iGcthLX3Yoh/JV5JADVZACliwbHdkjHm1IwIPvgRLOhKySdZBvGFA/oh/gEOAyMwMcp1nu0/JVmV3XR1gaM6n/WiJtetwo6xiz5j5DpxKJz1RzZ90CqtZ8ZJYLR1OHn4F9pV2l3UW7iBvMISpHtYvsiQdPSbbDpe5Eg2Bp7R1KyR4nzA2Y5xOt+aAWW/JTcj+k322irOJj2MIc28E1elcj/8LNUR3XUMyeE2TYO1OjxFfcTcg2ruNGrpGMxRvjJFudKhAMbjTrmNXUSbvNeVJM89pGwJ8bpwx9B0++c0W2QH6w8LRL3FRqjMDnX6Zi7Jy7fyl62GN/3KJKXp08Kz2kugViV/Iy9ggpPJ6R+tj4aKmWwm1mKK1tSarFGBoQ1jwiF9/g8DDNuMm6fmm/Ido6EZwVHxREEkv3PqpdZYjoEtUYjb6/iaf76fwLVn3e5uCo2tHgiDuvk7YRM040Pd3R+Fwe/iNOJ9XCxen4fJWWhTwEjNLPaGw=
